<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="13.0.1" />
        <PackageReference Include="Heron.MudCalendar" Version="2.0.3" />
        <PackageReference Include="Heron.MudTotalCalendar" Version="2.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.5" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
        <PackageReference Include="MudBlazor" Version="7.15.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\css\app.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\bootstrap\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\bootstrap\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="Features\Debt\Manage\Components\CreateDebtFormComponent.razor" />
      <_ContentIncludedByDefault Remove="Features\Debt\Manage\Components\DebtEntryComponent.razor" />
      <_ContentIncludedByDefault Remove="Features\Debt\Manage\Components\DebtManagementComponent.razor" />
      <_ContentIncludedByDefault Remove="Features\User\Deactivate\Components\DeactivateUserComponent.razor" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Features\FinancialRecord\DTOs\FinancialRecordModel.cs" />
    </ItemGroup>

</Project>
